### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by marchinram** [fogleman/nes#11]
I run the following:
<code>go get github.com/fogleman/nes</code>

And get the following output:
<code># pkg-config --cflags portaudio-2.0</code>
<code>Package portaudio-2.0 was not found in the pkg-config search path.</code>
<code>Perhaps you should add the directory containing `portaudio-2.0.pc' to the PKG_CONFIG_PATH environment variable</code>
<code>No package 'portaudio-2.0' found</code>
<code>pkg-config: exit status 1</code>

**Comment by fogleman** [comment]
The portaudio-go dependency requires portaudio on your system:

> To build portaudio-go, you must first have the PortAudio development headers and libraries installed. Some systems provide a package for this; e.g., on Ubuntu you would want to run apt-get install portaudio19-dev. On other systems you might have to install from source.

On Mac, you can use homebrew:

    brew install portaudio

**Comment by fogleman** [comment]
Updated readme with a note on this.

**Comment by marchinram** [comment]
Didn't seem to work for me:

```
Brians-MacBook-Pro-3:~ brianrojas$ brew install portaudio
Warning: portaudio-19.20140130 already installed
Brians-MacBook-Pro-3:~ brianrojas$ go get github.com/fogleman/nes
# pkg-config --cflags portaudio-2.0
Package portaudio-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `portaudio-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'portaudio-2.0' found
pkg-config: exit status 1
```

**Comment by fogleman** [comment]
Looks like you need to upgrade your portaudio version

**Comment by fogleman** [comment]
Nevermind, you have the same version I do.

**Comment by marchinram** [comment]
Any update on this?

**Comment by fogleman** [comment]
Have you tried uninstalling pkg-config and portaudio in homebrew and reinstalling them?

**Comment by marchinram** [comment]
Thx the problem turned out to be that portaudio wasn't in my PKG_CONFIG_PATH, thx for the help, really interested in how emulation works can't wait to start looking through your project!

**Comment by JohnWong** [comment]
I had the same problem.

**Comment by dilip2048** [comment]
> Thx the problem turned out to be that portaudio wasn't in my PKG_CONFIG_PATH, thx for the help, really interested in how emulation works can't wait to start looking through your project!

how did you add it?
