### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ponpal** [fogleman/nes#12]
Running "go get github.com/fogleman/nes" gives the following, concise output:
Segmentation fault

No bin folder is created under my GOPATH.

I'm running Linux Mint.

**Comment by fogleman** [comment]
What happens if you `go get` the dependencies? I'm guessing the problem is with one of the dependencies and not the `nes` package itself.

    go get github.com/go-gl/gl/v2.1/gl
    go get github.com/go-gl/glfw/v3.1/glfw
    go get code.google.com/p/portaudio-go/portaudio
