### ISSUE TITLE
[Newb Question] Go-gl can't find headers

### ISSUE THREAD

**Issue by StarScape** [fogleman/nes#13]
Alright, so admittedly this might be a stupid question, but I normally use a windows environment for development and have only recently started using Linux, mostly because it's damn hard to contribute to anything open source when you're running windows. Some of these configuration problems can be a bit baffling, so excuse the newbness.

Following the directions, I installed portaudio without any issue. But when I ran `go get github.com/fogleman/nes` I get this error:

    # github.com/go-gl/gl/v2.1/gl
    gocode/src/github.com/go-gl/gl/v2.1/gl/procaddr.go:52:21: fatal error: GL/glx.h: No such file or directory
      #include <GL/glx.h>
                         ^
    compilation terminated.
    # github.com/go-gl/glfw/v3.1/glfw
    In file included from gocode/src/github.com/go-gl/glfw/v3.1/glfw/context.go:4:0: glfw/include/GLFW/glfw3.h:153:21: fatal error: GL/gl.h: No such file or directory
       #include <GL/gl.h>
                         ^
    compilation terminated.

It's pretty obvious what's happening here: go-gl can't find the OpenGL headers. *Why,* I'm not quite sure. Does something in my system need to be pointing to the header files, or is this an actual bug? I'm running Xubuntu 14, if that's relevant.

**Comment by fogleman** [comment]
Not sure, you should file this against the go-gl/gl repo...

https://github.com/go-gl/gl

**Comment by abcdsxg** [comment]
I solve it by https://stackoverflow.com/questions/36371535/issues-with-golang-dependencies#36372239
