### ISSUE TITLE
Can't install on Ubuntu 15.10

### ISSUE THREAD

**Issue by shadow1163** [fogleman/nes#18]
My Ubuntu system had upgraded to Ubuntu 15.10, when ran command "go get github.com/fogleman/nes", go-gl can't compile.
@ubuntu:~$ go get github.com/fogleman/nes
# github.com/go-gl/glfw/v3.1/glfw
In file included from GoProject/src/github.com/go-gl/glfw/v3.1/glfw/context.go:4:0:
glfw/include/GLFW/glfw3.h:153:21: fatal error: GL/gl.h: No such file or directory
compilation terminated.
# github.com/go-gl/gl/v2.1/gl
GoProject/src/github.com/go-gl/gl/v2.1/gl/procaddr.go:52:21: fatal error: GL/glx.h: No such file or directory
compilation terminated.

**Comment by fogleman** [comment]
From the go-gl repo:

> On Ubuntu/Debian-based systems, the libgl1-mesa-dev package.

**Comment by shadow1163** [comment]
Ok, thank you.
