### ISSUE TITLE
error with go get github.com/fogleman/nes

### ISSUE THREAD

**Issue by cristianhoyos66** [fogleman/nes#20]
When I try to install the emulator I'm getting this output:

"# github.com/go-gl/glfw/v3.1/glfw
/usr/bin/ld: no se puede encontrar -lXi
collect2: error: ld returned 1 exit status"

When I look in $GOPATH/bin, nes is not installed.

Thank you.

**Comment by vitorarins** [comment]
In Ubuntu I had to install `libxi-dev`, that is probably your case too.

**Comment by cristianhoyos66** [comment]
Yeah, the answer from @vitorarins works
