### ISSUE TITLE
Go 1.6 runtime error

### ISSUE THREAD

**Issue by pawelropa** [fogleman/nes#21]
Hello Michael, 

I am really impressed with your implementation of nes emulator, so much so that I'm trying to implement my own (Swift + Metal). Was playing with your implementation, however after the update to go 1.6 I am no longer able to due to runtime error.

The problem exists for `go version go1.6.2 darwin/amd64` and here is the stack trace.

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running, locked to thread]:
panic(0x44e4660, 0xc820111a30)
	/usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/gordonklaus/portaudio._cgoCheckPointer1(0x43ed9a0, 0xc820096080, 0x0, 0x0, 0x0, 0x43ccde0)
	??:0 +0x4d
github.com/gordonklaus/portaudio.OpenStream(0x0, 0x0, 0x0, 0xc82006a360, 0x2, 0xd5d4a5, 0x40e5888000000000, 0x0, 0x0, 0xc820111a00, ...)
	/Users/pawel/go/src/github.com/gordonklaus/portaudio/portaudio.go:504 +0x3d1
github.com/fogleman/nes/ui.(*Audio).Start(0xc8200c9340, 0x0, 0x0)
	/Users/pawel/go/src/github.com/fogleman/nes/ui/audio.go:24 +0x192
github.com/fogleman/nes/ui.Run(0xc820111980, 0x1, 0x1)
	/Users/pawel/go/src/github.com/fogleman/nes/ui/run.go:33 +0xce
main.main()
	/Users/pawel/go/src/github.com/fogleman/nes/main.go:19 +0x13d
```

Kind regards,
Pawel

**Comment by fogleman** [comment]
This was an issue in the `portaudio` library. You just need to update it to the latest version. This will probably work:

    go get -u github.com/fogleman/nes

`-u` will update all the dependencies.

**Comment by pawelropa** [comment]
Thanks for swift response, issue resolved 👍
