### ISSUE TITLE
How to reset the loaded rom?

### ISSUE THREAD

**Issue by norbertfuhs** [fogleman/nes#25]
Hi I know this is just an awesome pet project, but I have a strage problem I played a game which crashed the music plays but their are there only an background color but now other spirites like the charecter and level objects or the game menu.. Is there any trick to solve this?

**Comment by fogleman** [comment]
Did you press R to reset?

**Comment by norbertfuhs** [comment]
Yes sorry for the stupid question! ;) After pressing R it works! Thanks for
the answer

2017-01-07 20:52 GMT+01:00 Michael Fogleman <notifications@github.com>:
