### ISSUE TITLE
USB Support for Controller

### ISSUE THREAD

**Issue by norbertfuhs** [fogleman/nes#30]
Hi,

I wonder if it would be difficult to add USB Controller Support for an USB SNES Gamepad so I could run this on my Raspberry Pi and have an sort of Go based NES Classic MINI alternative..

**Comment by fogleman** [comment]
Does that show up as a joystick to your computer? If so it should already work, might just need to tweak the hard-coded button mapping... https://github.com/fogleman/nes/blob/master/ui/util.go#L66-L94

**Comment by norbertfuhs** [comment]
Thanks. But I can forget the idea at least for the Raspi [go-gl/issues/76](https://github.com/go-gl/gl/issues/76)
