### ISSUE TITLE
Zero Page Indexed

### ISSUE THREAD

**Issue by optimisticninja** [fogleman/nes#32]
```
case modeZeroPageX:
    address = uint16(cpu.Read(cpu.PC+1) + cpu.X)

case modeZeroPageY:
    address = uint16(cpu.Read(cpu.PC+1) + cpu.Y)
```

I have yet to run or play with your code, Golang isn't exactly my domain. However, this doesn't appear to account for wrapping and always being on the zero page. Lets say 0xFF is in cpu.PC+1 and cpu.X is 3. The address returned would be 0x0102 not 0x0002. Same goes for Y.

I'm writing my own 6502 at the moment so please feel free to call me nuts since your emulator seems to work from the screenshots.

From: [Emulator 101](http://www.emulator101.com/6502-addressing-modes.html)
> Zero-Page Indexed
>
>This works just like absolute indexed, but the target address is limited to the first 0xFF bytes.
>
>The target address will wrap around and will always be in the zero page. If the instruction is LDA $C0,X, and X is $60, then the target address will be $20. $C0+$60 = $120, but the carry is discarded in the calculation of the target address.

**Comment by optimisticninja** [comment]
Proposed solution:

```
case modeZeroPageX:
    address = uint16(cpu.Read(cpu.PC+1) + cpu.X)
    address -= address & 0xFF00;

case modeZeroPageY:
    address = uint16(cpu.Read(cpu.PC+1) + cpu.Y)
    address -= address & 0xFF00;
```

**Comment by fogleman** [comment]
Good catch, thanks. Looks like this rarely happens. (I wasn't able to make it happen while running several different games.) Fixed.
