### ISSUE TITLE
Need help decoding an error message

### ISSUE THREAD

**Issue by russel** [fogleman/nes#9]
$ go get github.com/fogleman/nes
$ nes
2015/03/23 16:38:28 Usage: go run main.go rom_file.nes
$ nes ~/Downloads/Tetris.nes 
2015/03/23 16:40:16 unsupported mapper: 65
$ 

I am ambivalent about the usage message, it works for one developer situation but not for the full compiled one, which perhaps should be the norm?

Sadly I have no idea what mapper 65 is :-(

**Comment by fogleman** [comment]
http://wiki.nesdev.com/w/index.php/Mapper

My emulator cannot run this particular game because I haven't implemented that mapper.
